### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhp1254** [moneroexamples/spendkey#2]
spendkey/src/monero_headers.h:11:46: fatal error: cryptonote_core/cryptonote_basic.h: No such file or directory
compilation terminated.

**Comment by moneroexamples** [comment]
This example hasn't been updated in 2-3 years, and it is no longer maintained unfortunately. 

What do you want to do? Maybe other code examples which are currently active will help you?

**Comment by zhp1254** [comment]
im looking for some sdk that can  simple gen privkey and gen address with privkey .    i alos looking for same sdk that can create transaction hex with  vins    ,sign transaction hex with privkeys

**Comment by moneroexamples** [comment]
If you want this for C++, you can just use monero's own C++ api for all this. For javascript,  you can look into openmonero and mymonero frontends.

**Comment by zhp1254** [comment]
my c++ is poor , monero's source code is hard to me

**Comment by moneroexamples** [comment]
There is also python for monero:

https://old.reddit.com/r/Monero/comments/a1ni0r/a_reminder_for_python_developers_that_we_have_a/

Maybe this will be helpful?

**Comment by zhp1254** [comment]
the seeds part is helpful for me ,thanks a lot
the monero transfer is use wallet rpc api  ,that not work for me

**Comment by moneroexamples** [comment]
In this case, I think there are no more options that I am aware off. Maybe you will have more luck asking at https://monero.stackexchange.com/ ?

**Comment by zhp1254** [comment]
let me try out this  thaks again

**Comment by moneroexamples** [comment]
ok. I close the issue. If something, please feel free to reopen or make new one.
